# Generated by Django 4.1.2 on 2022-11-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category_type', models.CharField(choices=[('I', 'Income'), ('E', 'Expense'), ('D', 'Debt'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
