# Generated by Django 4.1.2 on 2022-11-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
